# Generated by Django 4.2.1 on 2023-05-13 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_module', '0002_alter_useranswer_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizresult',
            name='course',
        ),
        migrations.RemoveField(
            model_name='quizresult',
            name='user',
        ),
        migrations.AddField(
            model_name='quizresult',
            name='quiz_taker',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='quiz_module.quiztaker'),
            preserve_default=False,
        ),
    ]
