# Generated by Django 4.2.1 on 2023-05-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_module', '0003_remove_quizresult_course_remove_quizresult_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizresult',
            name='total_correct',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='total_incorrect',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='total_questions',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
