# Generated by Django 4.2.1 on 2023-05-22 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_module', '0004_alter_quizresult_total_correct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
